#pragma once

#define TRACKER_DEFAULT_PORT 9000

#define MAX_PEER 1024

#define ERROR_CMD 0
#define REGISTER 1
#define REGISTER_SUCCESS REGISTER
#define REGISTER_FAIL -REGISTER
#define LOGIN 2
#define LOGIN_SUCCESS LOGIN
#define LOGIN_FAIL -LOGIN
#define UPLOAD 3
#define UPLOAD_SUCCESS UPLOAD
#define UPLOAD_FAIL -UPLOAD